/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#eca5b0",
        "surface-container": "#1d1f26",
        "inverse-primary": "#705d00",
        "surface-variant": "#33343b",
        "on-secondary-fixed-variant": "#6b3741",
        "surface-bright": "#373940",
        "tertiary-container": "#d3dbe0",
        "background": "#111319",
        "on-surface-variant": "#d0c6ab",
        "surface-container-lowest": "#0c0e14",
        "on-tertiary-container": "#586065",
        "tertiary-fixed": "#dce4e9",
        "on-primary-fixed-variant": "#544600",
        "error": "#ffb4ab",
        "secondary": "#fcb3be",
        "on-primary-fixed": "#221b00",
        "on-tertiary": "#2a3136",
        "outline-variant": "#4d4732",
        "error-container": "#93000a",
        "surface-tint": "#e9c400",
        "on-secondary": "#50212b",
        "secondary-fixed-dim": "#fcb3be",
        "secondary-fixed": "#ffd9de",
        "primary-fixed-dim": "#e9c400",
        "surface-container-highest": "#33343b",
        "tertiary-fixed-dim": "#c0c8cd",
        "primary": "#fff6df",
        "on-surface": "#e2e2eb",
        "surface-container-high": "#282a30",
        "primary-container": "#ffd700",
        "inverse-surface": "#e2e2eb",
        "on-primary-container": "#705e00",
        "surface-container-low": "#191b22",
        "on-secondary-fixed": "#360c17",
        "on-error": "#690005",
        "secondary-container": "#6e3943",
        "tertiary": "#f0f7fd",
        "on-tertiary-fixed": "#151d21",
        "inverse-on-surface": "#2e3037",
        "on-tertiary-fixed-variant": "#40484c",
        "on-error-container": "#ffdad6",
        "surface-dim": "#111319",
        "on-primary": "#3a3000",
        "surface": "#111319",
        "on-background": "#e2e2eb",
        "primary-fixed": "#ffe16d",
        "outline": "#999077"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "gutter-sm": "12px",
        "base": "4px",
        "column-gap": "24px",
        "gutter-md": "24px",
        "xs": "8px",
        "margin": "32px",
        "xl": "64px",
        "lg": "40px",
        "sm": "16px",
        "md": "24px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "code-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}